version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      gha:
        patterns: ["*"]
    open-pull-requests-limit: 3

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      tokio-stack:
        patterns: ["tokio*", "reqwest*"]
      everything-else:
        patterns: ["*"]
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /image
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    open-pull-requests-limit: 3
